apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/S3sc0/aamzouar
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
