Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.box_check_update = false
  config.vm.hostname = "hrhirhaS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |v|
	v.name = "hrhirhaS" 
    v.memory = 2048
	v.cpus = 1
  end
  
  config.vm.provision "shell" do |s|
	s.env = {"K3S_TOKEN" => "12345", "K3S_KUBECONFIG_MODE" => "644"}
	s.inline = <<-SHELL
	  curl -sfL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110
	  sudo apk add helm
    SHELL
  end

  config.vm.provision "file" do |f|
    f.source = "~/Desktop/inception_of_things/p2/hello-kubernetes"
    f.destination = "~/"
  end

  config.vm.provision "file" do |f|
    f.source = "~/Desktop/inception_of_things/p2/ingress-test.yaml"
    f.destination = "~/"
  end

  config.vm.provision "shell", after: :all do |s|
    s.env = {"KUBECONFIG" => "/etc/rancher/k3s/k3s.yaml"}
    s.inline = <<-SHELL
	  kubectl apply -f ingress-test.yaml
	  helm install app-one ./hello-kubernetes/deploy/helm/hello-kubernetes \
	  --set ingress.configured=true \
	  --set ingress.pathPrefix="/" \
	  --set service.type="ClusterIP" \
	  --set deployment.replicaCount=1 \
	  --set message="Hello from app1"
	SHELL
  end
end
