Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.box_check_update = false
  config.vm.hostname = "hrhirhaS"
  config.vm.network "private_network", ip: "192.168.56.110"
  #config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |v|
	v.name = "hrhirhaS" 
    v.memory = 2048
	v.cpus = 1
    v.customize ["modifyvm", :id, "--vram", "16"]
  end
  
  config.vm.provision "shell" do |s|
	s.env = {"K3S_TOKEN" => "12345",
            "K3S_KUBECONFIG_MODE" => "644",
            "INSTALL_K3S_VERSION" => "v1.30.5+k3s1"}
	s.inline = <<-SHELL
      /usr/bin/curl -sfL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110
    SHELL
  end

  config.vm.provision "file" do |f|
    f.source = "./apps"
    f.destination = "~/"
  end

  config.vm.provision "shell", after: :all do |s|
    s.inline = <<-SHELL
      /bin/sleep 20
      /usr/local/bin/kubectl get nodes -o wide
	  /usr/local/bin/kubectl apply -f apps/ingress.yaml
      /usr/local/bin/kubectl apply -f apps/app-one.yaml
      /usr/local/bin/kubectl apply -f apps/app-two.yaml
      /usr/local/bin/kubectl apply -f apps/app-three.yaml
	SHELL
  end
end
