Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.box_check_update = false

  config.vm.define "mS" do |server|
    server.vm.hostname = "mS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
	  v.name = "mS" 
      v.memory = 1024
	  v.cpus = 1
    end
    server.vm.provision "shell" do |s|
	  s.env = {"K3S_TOKEN" => "12345", "K3S_KUBECONFIG_MODE" => "644"}
	  s.inline = <<-SHELL
	    curl -sfL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110
      SHELL
	end
  end 

  config.vm.define "mSW" do |agent|
    agent.vm.hostname = "mSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |v|
	  v.name = "mSW" 
      v.memory = 1024
	  v.cpus = 1
    end
    agent.vm.provision "shell" do |s|
	  s.env = {"K3S_URL" => "https://192.168.56.110:6443", "K3S_TOKEN" => "12345"}
	  s.inline = <<-SHELL
	    curl -sfL https://get.k3s.io | sh -s - agent --node-ip 192.168.56.111
      SHELL
	end
  end 

end
