Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/bionic64"
    config.vm.hostname = "bonus" 
    config.vm.network "private_network", ip: "192.168.56.110"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "bonus"
      vb.customize [
        "modifyvm", :id,
        "--cpus", "8",
        "--memory", "12000",
      ]
    end

end
